### ISSUE TITLE
DLC links are broken

### ISSUE THREAD

**Issue by zee5679** [C0Assassin/RB4-to-RB2#10]
Can't download the DLC as the url doesnt work? Its been like this for awhile is something in the works?

**Comment by jnackmclain** [comment]
DLC no longer easily can be packed together with onyx due to contexts custom post processing. the packs also haven't been updated in a long time.

**Comment by jnackmclain** [comment]
ill make new packs anyways tho

**Comment by jnackmclain** [comment]
I lied im not making packs
the contexts issue is really annoying sorry

**Comment by zee5679** [comment]
all good like I can still pull the stuff from the github and use it with rpcs3 couldnt I?

**Comment by jnackmclain** [comment]
Should be
