### ISSUE TITLE
Older DLC songs?

### ISSUE THREAD

**Issue by GucciGuwop420** [C0Assassin/RB4-to-RB2#11]
Im looking for two older RB4 dlc songs. Alice in Chains - Down in a Hole and AFI - Far Too Near. If I buy or gift these songs to some one on here can they get converted to RB2? Sorry if this is a dumb question.

**Comment by C0Assassin** [comment]
How do u plan to get the songs off from ur ps4 or xbone?

**Comment by GucciGuwop420** [comment]
Usb flash drive?

**Comment by LlysiX** [comment]
tell me you don't know the transfer procedure without telling me you don't know the transfer procedure

**Comment by GucciGuwop420** [comment]
Floppy disc?

**Comment by jnackmclain** [comment]
Rock Band 4 content is encrypted. You buying a song does nothing for this project. A USB flash drive also does nothing for this project.

**Comment by GucciGuwop420** [comment]
Ok sorry just trying to help.

**Comment by C0Assassin** [comment]
> Ok sorry just trying to help.

Appreciate u trying to help, but there's a reason why alot of people arent doing this. Its not easy to get ahold of the dlc files, and the conversion process is not simple or automatic.
