### ISSUE TITLE
Not Really an "Issue", But More of a Question...

### ISSUE THREAD

**Issue by JarenM03** [C0Assassin/rb4-to-rb2#11]
So, I noticed that the main contributor to this project uploaded a conversion of the song "Goodbye, Good Luck". I don't mean to ask a dumb/silly question, and I apologize if this is not the forum to ask in, but does this title imply that there are to be no more new conversions added? If that is the case, then I do understand; all good things must come to an end, after all. Nonetheless, I sincerely hope that the aforementioned song name is merely a coincidence. I was genuinely curious, and figured I would ask to be sure. :)

**Comment by jacket430** [comment]
Every song title is actually directly telling you something they're going to do. Watch out, some are pretty scary.

**Comment by JarenM03** [comment]
> Every song title is actually directly telling you something they're going to do. Watch out, some are pretty scary.

Bwahaha, I hope I don't contract "Pac-Man Fever" anytime soon. Otherwise, I'll fall "Sick, Sick, Sick", and quickly proclaim "It Hurts"! "In the End", I would hate to "Wake Up Dead". 

Seriously though, I only asked because a guitarist I knew made his last video on his YouTube platform a literal title reference: "The End" by The Beatles. I was wondering if the same thing was happening here, even though I honestly doubted it.

**Comment by C0Assassin** [comment]
Just a coincidence.

**Comment by JarenM03** [comment]
> Just a coincidence. 

I am very glad to hear that. All the effort you put into this project is simply amazing, and I very much appreciate each and every one of your contributions.
