### ISSUE TITLE
How to download just spesific songs?

### ISSUE THREAD

**Issue by indra-constantine** [C0Assassin/RB4-to-RB2#12]
I just need thestage, but if i clone this repo with this link https://github.com/C0Assassin/RB4-to-RB2
its will download everything from this repo, i tried clone this link https://github.com/C0Assassin/RB4-to-RB2/tree/main/RB4%20DLC/songs/thestage

its ask me username & password

i'm still new on github

**Comment by C0Assassin** [comment]
You can individually click all the 6 or 7 files that make up the song, and download them that way.

Alternatively, you can go to the Xbox branch and download the cons by click the con name and clicking download.

**Comment by ApexJohn** [comment]
This no longer works. There is no Xbox branch and CON files are shoved into one in the artifacts from actions, which makes it impossible to pack back into a CON and convert it to Clone Hero.

**Comment by C0Assassin** [comment]
https://drive.google.com/drive/folders/1hs6_4Va38hNPY3wZrz47ISiswTOeKzp4?usp=share_link
Clone Hero players should not use this repo, but rather this link to an unaffiliated RB4 to CH project.
The repo is solely meant for Rock Band players only.
