### ISSUE TITLE
DTA files getting harder to parse

### ISSUE THREAD

**Issue by afestini** [C0Assassin/rb4-to-rb2#14]
First off: is there any documentation describing the format or some "official" files as references?

In my project I added support to play/stream from con files directly, since it's just a more efficient way than several single files (plus, mogg using channels for the instruments means everything is always in sync, whereas split ogg streams are a nightmare).

Back to DTA. The first files I saw seemed to follow a simple concept that made the files very easy to parse and avoided all ambiguity:
-Block/field names in single quotes
-String values in double quotes
-numbers without quotes

The above is a simple convention that easily distinguishes named data (fields or structs) from sequences (array, list, whatever you want to call them)

Recently it seems that quotes are getting more and more removed or used interchangeably, making it a bigger and bigger pain to parse the files and requiring more and more domain specific workarounds and tea leaf reading. Some examples:

('A' "B") => key - value, the field or block has a name (A) and the value (B)
("A" "B") => variable size sequence/list of strings with values A, B
(1 2) => variable size sequence of numbers
('1' 2) => key - value, name (1) and value (2)
('A' 1 2) => block with name (A) and fixed number of values (1, 2), usually having a predefined meaning (like start and duration of a song preview)

By removing quotes or mixing them, things get confusing
(A B): does it mean field A has value B or is this a list of two strings?
(1 ...)  is this a name that happens to be a number or the start of a sequence?

I don't know if the older files I saw were sticking to the original file format or someone did it arbitrarily, but the pattern of ' and " having a clear meaning made for a very simple, elegant and pretty clever file format.

I don't know if that was a fluke or if recent files are the result of files being authored based on "I don't understand the point of it and they seem to work without". After updating the repo to the latest version, where it should be many more songs, instead a whole lot stopped loading and will require rather ugly workarounds.

**Comment by DarkRTA** [comment]
If you are having to add all sorts of ugly workarounds its likely because your parser is bad and not accepting everything the game itself does. DTA is best treated as if its a programming language (it practically is to some extent) so you will either want to use a parser generator, or hand-write a recursive descent parser for it. We currently don't have a formal grammar that can be ported to a parser generator, but it shouldn't be too hard to come up with one.

**Comment by C0Assassin** [comment]
There are 3 different DTA templates/styles that I have used over the course of this project. All with their own quirks and ways of producing a songs dta.

The first is Onyx, which is automatically generated upon conversions or processes.
You can see these during the early songs. Like Hot For Teacher or Brown Eyed Girl.
I dont prefer these, and eventually later on, ill be replacing them. It puts quotes or apostrophes on almost everything, and loads of spacing and line breaks to make it more legible for novice users.

The second was a template based off HMXs own official DTAs, circa 2009 and 2010, complete with dev comments. You can see these around the middle of the life of the project. I love using these, but it required everything to be transferred and filled manually from the rb4 dta.

And the third is an automatic dta script, created by addymills. It allows me to mostly fill out a dta exactly as method 2, but without any manual input from me. So it saves me a lot of time. This can be seen in some of the latest song releases. Any song released in the last month or so has this type, and ill be using these in the future moving forward.

Hope that explains some of the nuisances and differences. They all work just fine ingame, so if theres problems with some tool not being able to parse them correctly, thats out of my hands.

**Comment by afestini** [comment]
> DTA is best treated as if its a programming language (it practically is to some extent) so you will either want to use a parser generator, or hand-write a recursive descent parser for it.

Unless there are much more complex files I haven't seen, I absolutely can't see how it is anything like a programming language. Other than #ifdefs, I see nothing that isn't plain nested data, even if the amount of "(" is triggering some Lisp related PTSD.

What I see are two types of blocks:
-Named block with either nested block(s) or value(s)
-Unnamed sequences

Also three types of data (based on the old Onyx files, which broke their own convention in some places):
-'names' (for blocks or variables)
-"strings" (important distinction to disambiguate names from values, which matters for sequences)
-1234 or 12.34 (numbers, integer or float)

This is even more trivial than JSON or YAML. In fact, based on the old files I saw, I would be tempted to treat DTA as a very viable alternative to the above, since other than the way structs {} are distinct from arrays [], no explicit "null" and no bools (easily substituted by number), DTA is extremely similar to JSON.

So my OCD is going into overdrive at the thought of over-engineering and throwing grammar based parser generators at a format that can be parsed in way less than 100 lines of code... IF the files adhere to the simple rules above as observed in the old onyx files (with two frustrating exceptions, the cue files and the unquoted  midi_file). Of course, this might just be me being traumatized from boost spirit, the insane compile times and unusably slow debug builds (when rewriting the parser turns 30s into 50ms, you know something was VERY wrong).

That is the main reason why I wondered if there is any official format definition. If this format was completely made up by HMX and never officially defined how to use quotes, I will just have to accept it as "well, they were THAT close to create a really awesome little format and messed it up right before the finishing line".

If DTA is a more commonly used format, I would have a different view. For example, you can write a JSON parser that handles unquoted strings. There probably are some that would happily accept that. But that wouldn't make such a file any less invalid and wrong.

The problem here is that no official specifications exist (at least I couldn't find any) and everything is based on reverse engineering and trial and error. So to some degree I have to agree with you: the official parser (black box as it may be) is unfortunately the only reference.

I'm trying not to let my project turn into Rock Band and spend straight up MINUTES scanning for songs. Currently scanning the entire song library (around 5000 songs) takes under 4s uncached (meaning, data has to be read from SSD) and 25ms cached (every start after the first, thanks to Windows and its aggressive file caching).

**Comment by afestini** [comment]
> There are 3 different DTA templates/styles that I have used over the course of this project. All with their own quirks and ways of producing a songs dta.

I looked at those two songs and it seems even those were not consistent. I wonder if Onyx itself had more than one person working on it or some parts were added later by someone else. It looks so close to a cleverly defined and efficient format.

I don't think I would agree with the idea that the quotes were intended to make them novice friendly. If anything, a casual user would likely be confused by why on earth the file is using two different types of quotes... until they write a parser for it and start seeing the beauty in this simple but important difference.

I'll have to dig through the repo history to find some example for those HMX based files. They are probably the best bet when it comes to understanding how HMX intended the format to work (OCD sucks, but when there is a "how it's supposed to be", anything going against that can drive me crazy).

Obviously having to do that manually is not great, not just for the extra work, but because anything done manually is likely to have bugs. So I can see why the third option is the preferred one.

**Comment by LlysiX** [comment]
> Unless there are much more complex files I haven't seen, I absolutely can't see how it is anything like a programming language. 

If you have only looked at song DTAs, you're definitely missing a lot of complexity. Most of the games internals are run off of DTA. I'd definitely recommend taking a look at the [milo-script-library](https://github.com/hmxmilohax/milo-script-library) if you want to see how dta is used outside of songs (especially the rb1 ps2 scripts, which are the ones that are the original HMX DTAs that were mentioned earlier).

> Other than #ifdefs, I see nothing that isn't plain nested data, even if the amount of "(" is triggering some Lisp related PTSD.

DTA is pretty much a HMX made subset of Lisp. Lisp is the language DTA is attributed to on the script library.

**Comment by DarkRTA** [comment]
> So my OCD is going into overdrive at the thought of over-engineering and throwing grammar based parser generators at a format that can be parsed in way less than 100 lines of code... IF the files adhere to the simple rules above as observed in the old onyx files (with two frustrating exceptions, the cue files and the unquoted midi_file).

That's the thing. If you were to look at @LlysiX's comment, you'd find that DTA isn't as simple of a format as it seems at first glance. Its less of a data format, and more of a half-baked lisp. We've got 2 known example of parsers that can handle the format if you want to reference them. [1] [2]

> Of course, this might just be me being traumatized from boost spirit, the insane compile times and unusably slow debug builds (when rewriting the parser turns 30s into 50ms, you know something was VERY wrong).

This is more of just boost being *horrible*. A parser generator isn't going too add to much to your compile times (or even run times for that matter), and there's always the option of biting the bullet and learning how to properly write a recursive descent parser. As a nice plus, you'd end up with a parser that's way easier to extend if you come across more cases that your parser can't handle correctly.

[1] - https://github.com/maxton/DtxCS
[2] - https://github.com/mtolly/dtab

**Comment by afestini** [comment]
That's some great sources to dig into. With Google I usually find little to nothing and the information tends to be superficial. And I thought I was just joking about it looking like Lisp.

I might still get lucky in that I don't need the majority of the data and parsing-wise it's easy to just ignore blocks that aren't needed. Whether the parser is a "proper" recursive decent parser is extremely debatable, but it is recursively descending and pretty much depth-first traversing the blocks. Beyond that it's not doing much other than passing the encountered data to some callbacks (when building the song list, I care about very different parts of the file compared to loading a song, so I can have "specific" parsing on top of the generic core parsing).
