### ISSUE TITLE
Why did the project format change? I can no longer drag and drop into the BLUS30050\USRDIR folder

### ISSUE THREAD

**Issue by wesmwitt** [C0Assassin/rb4-to-rb2#2]
Unless I am mistaken this project used to have folders such as "RB4 - On Disc" containing the subfolder "songs" and then folders named "songname" containing all the standard rock band song files. Now all the folders just contain a files named after the songs with no extension type. 

Is there a new way to install or handle these files? They're no longer working as drag and drop on my setup. The readme still tells you to just drag and drop the folders. 

Thanks for the info.

**Comment by thoudankeykang** [comment]
use https://github.com/mtolly/onyxite-customs to build a ps3 pack from these songs in con format

**Comment by thoudankeykang** [comment]
correction the songs are in con format, use onyx to build a ps3 pkg pack of these songs

**Comment by LocalH** [comment]
For further info, the way it was done previously (with separate unencrypted moggs for 360 and encrypted ones for PS3) was causing build actions to fail because the repo was too big for the action runner. So now, the repo only contains 360 CONs, which Onyx can easily build into proper PS3 PKGs, complete with custom USRDIR folder name if you wish.

**Comment by jnackmclain** [comment]
For further, further info, the new GitHub file formatting allows for users to individually download singular songs directly from the web ui without downloading the entire repo locally as well. Ps3 pkgs can be found in the actions tab of this repo, pre built and ready for installation of the full suite of songs

**Comment by jnackmclain** [comment]
I lied, the actions don't have pkgs. my bad

**Comment by C0Assassin** [comment]
Essentially it boils down to repo health. Hosting just 360 cons is much more streamlined and doesn't bog down the repo with extra storage, and PS3/RPCS3 users can easily just use the quick convert option in Onyx to make PKG versions.
