### ISSUE TITLE
"I Gotta Feeling" not placed in RB4 DLC category in RB3DX

### ISSUE THREAD

**Issue by SCOTT0852** [C0Assassin/RB4-to-RB2#2]
Unlike the rest of the RB4 DLC songs, I Gotta Feeling is placed under the "Downloaded Songs" category when using Rock Band 3 Deluxe.
![image](https://user-images.githubusercontent.com/33875157/173293994-2bcea1f5-c459-4bed-8fd9-7c038ab28362.png)
![image](https://user-images.githubusercontent.com/33875157/173294044-f6f721d5-4706-4dcc-a2c5-068b3628f37b.png)

**Comment by wesmwitt** [comment]
> Unlike the rest of the RB4 DLC songs, I Gotta Feeling is placed under the "Downloaded Songs" category when using Rock Band 3 Deluxe. ![image](https://user-images.githubusercontent.com/33875157/173293994-2bcea1f5-c459-4bed-8fd9-7c038ab28362.png) ![image](https://user-images.githubusercontent.com/33875157/173294044-f6f721d5-4706-4dcc-a2c5-068b3628f37b.png)

Hi, where do I find a download for RB3DX? I can only seem to find RB2DX. Thanks.

Also thanks to the folks working on the RB4 DLC project!

**Comment by SCOTT0852** [comment]
> Hi, where do I find a download for RB3DX? I can only seem to find RB2DX. Thanks.

https://github.com/jnackmclain/rock-band-3-deluxe/

**Comment by C0Assassin** [comment]
Thanks for bringing this to my attention, not sure how this hiccup happened.

Fixed in the latest commit. 
https://github.com/C0Assassin/RB4-to-RB2/commit/3102109ff3d6fedc8cea6e4e092f894261e8d3a7
