### ISSUE TITLE
Autogen?

### ISSUE THREAD

**Issue by rb4dlcfan** [C0Assassin/rb4-to-rb2#32]
Sorry for the silly question, but what are the autogen charts exactly? Are they recreated charts with AI (in the case of lower difficulties) or something?

**Comment by C0Assassin** [comment]
No, they use the real midis and real mogg. But the animations, venue, and lipsyncing are auto generated by Onyx and are not hand crafted quality like a proper conversion would be.

This was all alluded to on the main page.

**Comment by rb4dlcfan** [comment]
Thanks for the answer!
