### ISSUE TITLE
Are Autogen charts identical?

### ISSUE THREAD

**Issue by pokeyjojo** [C0Assassin/rb4-to-rb2#33]
Hello! I’m wondering if the auto gen charts have identical charts to the rb4 versions? I don’t really care about the lip syncing just if all instruments work with the same chart. Want to know before I go through the whole process of adding a bunch of songs 

side note: is there ANY WAY to turn off the foot pedal in RB3. Really would like to do that somehow.

**Comment by pokeyjojo** [comment]
Found out Rock band 3 deluxe can turn off the foot pedal. Still wondering about the auto gen charts though

**Comment by jnackmclain** [comment]
yes, the "autogen" is in reference to the venue and lipsync. the charts are 1:1
