### ISSUE TITLE
Juke Box Hero - Lou Gramm Mick Jones missing from autogen

### ISSUE THREAD

**Issue by pokeyjojo** [C0Assassin/rb4-to-rb2#34]
Hello! Unless I’m missing something, The song “juke box hero” by Lou Gramm Mick Jones is missing. If you have the instructions to create an autogen chart I could just do that? Thanks!

**Comment by jnackmclain** [comment]
Jukebox hero is rock band 1 era dlc. this repo only covers songs released in rock band 4
