### ISSUE TITLE
How to manually convert DLC?

### ISSUE THREAD

**Issue by pokeyjojo** [C0Assassin/rb4-to-rb2#35]
Hello! Wondering if you could provide some instructions (maybe in the readme or something)about the process where you convert the songs manually(so venue's and animatiuons line up) would  love to be able to manually translate some songs here, it may not be that simple though, thanks!

**Comment by C0Assassin** [comment]
The steps to do so would require a couple of days to pen up, since everything needs to be written up. Thats not even including things that are prerequisites like Python scripts and Reaper charting. 

Ill see what I can come up with, but i cant guarantee anything.

**Comment by TrippyTCG** [comment]
a start would be to download the ".midi" file for the song, and use "Converthero" to convert the ".midi" file to a ".chart" file. then add the ".chart" file to to a program called "moonscraper".

https://www.youtube.com/watch?v=ZP0XTYkLhF8&t=101s

^^ this video helped me

**Comment by LocalH** [comment]
to be honest that advice will not really help at all with regards to authoring suitable venues for ports of the songs in question to rb2

**Comment by C0Assassin** [comment]
You gotta take into account where you source the midi from. You cant just pull it from Chorus, or some spreadsheet. It needs to be directly pulled from one of the ps4 packages for it to be considered a true conversion.

**Comment by TrippyTCG** [comment]
yeah I'm super beginner at this. still learning everyday. what yall doing there is like next level stuff. yall are smart to know how to do that lol

**Comment by C0Assassin** [comment]
Looks like you're in luck, Onyx's newest update that is rolling out has RB4 converting built within.
Which will convert venues into RB3 format, and possibly lipsyncs as well.

This was as far as I had gotten with the manual tutorial, and that was mostly just all setup. Only like a quarter of the entire process was written up. (I suck at writing up tutorials)
[Full Conversion Tutorial.docx](https://github.com/C0Assassin/rb4-to-rb2/files/15003667/Full.Conversion.Tutorial.docx)
