### ISSUE TITLE
Vocal Stem Sourcing

### ISSUE THREAD

**Issue by Brwinslow** [C0Assassin/rb4-to-rb2#37]
I'm trying to replicate my old Rockband 4 library on PC now. Notably, my friends and I play with all vocals muted for the true Karaoke experience. The vast majority of songs appear to have original stems that properly mute. Some of these stems appear to have vocals that were removed with AI. Is there a way to see which songs are have real stems and which have reverse engineered stems? Is there a plan in the future to extract the original stems? 

Thanks for your hard work! I really appreciate it!

**Comment by jnackmclain** [comment]
This repo contains stems as they came directly from rock band 4. Rock band 4 started using AI stems itself so that just how they are from the source.

**Comment by Brwinslow** [comment]
Very interesting. Thanks for the reply. I'm looking at One by U2 and Wake Me Up by Avicci as examples and I'm relatively sure the stems are different from my original copy. Even if they were done with AI by Harmonix, there seems to be strange errors, like the volume suddenly dramatically increasing when the vocals stop and then the volume snapping down with no fade when vocals start.

**Comment by C0Assassin** [comment]
Don't know what to tell you. They come directly from the ps4 packages.

As in, we go into RB4. Download song. Decrypt song off from PS4. Plop song into these packages. They're never touched.
