### ISSUE TITLE
Installation instructions unclear.

### ISSUE THREAD

**Issue by kcpwnsgman** [C0Assassin/rb4-to-rb2#4]
I'm having difficulty understanding how this is supposed to work and installed into Rock Band 3 deluxe and RPCS3,  I have the repository cloned and pulled and files don't have extensions. According to a closed issue (#2 ) the project format has changed, and Onyx needs to be used to create convert and create pkg files for RPCS3. At the very least this information should be included within the instructions.txt because as it stands, it implies the the files in the repository should be dropped in directly to the USRDIR folder, leading to a bit of frustration before realizing they need to be converted to be usable with RPCS3. After discovering this, it was easy enough to run the quick convert and repackage them for use on PS3.

**Comment by C0Assassin** [comment]
Ah yea, the instructions.txt is probably outdated now due to the repo format change. Thanks for that, I'll get to changing it.
