### ISSUE TITLE
Auto-converted songs don't work

### ISSUE THREAD

**Issue by oathbound01** [C0Assassin/rb4-to-rb2#40]
When I try to access the AUTOGEN songs on RB3 (both the unmodified disc version and RB3DX) on my PlayStation 3 all the songs that are AUTOGENned from RB4 appear greyed out and crash the game upon selection.

Are they only meant to be placeholders? All hand conversion (passed through Onyx of course) work beautifully on OG hardware, both on DX and standard RB3. Am I missing something?

**Comment by LinosM** [comment]
Set your parental control level to off, this is due to the autogened songs being unrated, blocking you from playing it

![image](https://github.com/C0Assassin/rb4-to-rb2/assets/15615513/355939f4-97b1-4511-9a81-cbc1fbbf9d87)

**Comment by oathbound01** [comment]
Wow, really? And this causes a full game crash? Pretty hilarious.

I'll try it as soon as I'm able to, many thanks.
