### ISSUE TITLE
Mogg File Index Error

### ISSUE THREAD

**Issue by LateNate9385** [C0Assassin/rb4-to-rb2#42]
When I try to convert Angel of Death by Slayer to a file usable with Clone Hero, I get an error "Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index." It may just be an issue with the version I downloaded, but I thought I might as well mention it.

**Comment by C0Assassin** [comment]
Duplicate issue, Issue has already been brought up here: https://github.com/C0Assassin/rb4-to-rb2/issues/41

Plus you shouldnt even be running these thru Onyx for games these are not supported for. (YARG, CH, PS)
There are dedicated projects specifically for them already in existance, this project is not it.

**Comment by C0Assassin** [comment]
I suggest reading here as to why i dont recommend converting these. And the comment below it, showing you the dedicated ch project.

https://github.com/C0Assassin/rb4-to-rb2/issues/38#issuecomment-2035764393

**Comment by LateNate9385** [comment]
Okay, thank you for the link. I found this project yesterday and downloaded/converted the files. I was unaware that they were not supposed to be converted. Thanks for explaining.

**Comment by C0Assassin** [comment]
Gotcha, understandable. I do have it right on the front page in bold letters, but I guess its easily missable idk.

https://cdn.discordapp.com/attachments/1131046106067902464/1232510512923672666/image.png?ex=6629b85d&is=662866dd&hm=6bb1844503f5b6a537e230c85da13cb7fbbe3b9c0b530233899beeb52a44461d&

**Comment by LateNate9385** [comment]
The reason why I didn't understand is because I was using a different type of converter I found online a couple days ago called Nautilus. I'm relatively new to Clone Hero and I have never used Onyx before so I just ignored the message because I assumed that it was irrelevant to me.
