### ISSUE TITLE
Cold Heart (PNAU remix) by Elton John and Dua Lipa file not working

### ISSUE THREAD

**Issue by chintwo123** [C0Assassin/rb4-to-rb2#43]
When dragging the file into Onyx, there is an error saying 'No songs found!'

Warning: Expected a single chunk, but found: [Braces (Tree {nodeID = 0, treeChunks = [Var "world",Sym "iterate",Sym "PostProc",Var "p",Braces (Tree {nodeID = 0, treeChunks = [Var "p",Sym "set",Sym "contrast",Int 30]})]}),Braces (Tree {nodeID = 0, treeChunks = [Var "world",Sym "iterate",Sym "PostProc",Var "p",Braces (Tree {nodeID = 0, treeChunks = [Var "p",Sym "set",Sym "saturation",Int 30]})]})]
Context (innermost first):
  - optional key "context"
  - parsing SongPackage
  - songs.dta entry #1 (starting from 1)
  - searching: /Users/chintwo/Downloads/Elton John - Dua Lipa - Cold Heart (PNAU R (1)
ERROR! No songs found!

**Comment by C0Assassin** [comment]
Refer to this, not fixing.
 https://github.com/C0Assassin/rb4-to-rb2/issues/38#issuecomment-2035764393
