### ISSUE TITLE
Can't Hold Us (ft. Ray Dalton)  by Macklemore and Ryan Lewis file not working

### ISSUE THREAD

**Issue by chintwo123** [C0Assassin/rb4-to-rb2#44]
Error when opening file in Onyx stating 'No songs found!'

Warning: Expected integer, but found: Braces (Tree {nodeID = 0, treeChunks = [Var "world",Sym "iterate",Sym "PostProc",Var "p",Braces (Tree {nodeID = 0, treeChunks = [Var "p",Sym "set",Sym "saturation",Int 50]})]})
Context (innermost first):
  - single chunk
  - optional key "context"
  - parsing SongPackage
  - songs.dta entry #1 (starting from 1)
  - searching: /Users/chintwo/Downloads/Macklemore & Ryan Lewis ft. Ray Dalton - C
ERROR! No songs found!

**Comment by C0Assassin** [comment]
Refer to this, not fixing.
https://github.com/C0Assassin/rb4-to-rb2/issues/38#issuecomment-2035764393
