### ISSUE TITLE
Unable to load song, skipping

### ISSUE THREAD

**Issue by Otakufreaks27** [C0Assassin/RB4-to-RB2#5]
Excuse me, I had errors "unable to load song, skipping" on Rock You Like A Hurricane by Scorpions, I just download all bin files but .pan file alone, and .dta had copying from site & pasteing to my .dta on RB4toRB2-DLC/songs (I'm on PS3).
IDK whats wrong with my files, please help me to fix it 🙏🏻

**Comment by C0Assassin** [comment]
Redownload the song and repackage it, is the best advice I can give you. The song has no problems far as I'm aware.

**Comment by Otakufreaks27** [comment]
How to repackaged it? Can C3 con tools do it?

**Comment by Otakufreaks27** [comment]
How to repackaged it? Can C3 con tools do it?
