### ISSUE TITLE
King For a Day and Cant Hold Us

### ISSUE THREAD

**Issue by nfbible2** [C0Assassin/rb4-to-rb2#68]
![king](https://github.com/user-attachments/assets/1e05e8f2-e54a-4abb-9f35-8b6aeb62e003)
I am having issues with just this song and Cant Hold Us by Macklemore where it shows that there is no song that can be loaded. I have put a photo in the issue.

**Comment by C0Assassin** [comment]
Theres like 3 or 4 different issues that specify King for a Day, go read one of those to find your answer. 

Short tldr: It works as intended in rb1 2 lego and 3.
