### ISSUE TITLE
Starlight (Muse) not in PS3 package?

### ISSUE THREAD

**Issue by paulsd95** [C0Assassin/RB4-to-RB2#7]
Downloaded the PS3 package yesterday and the only Starlight in it was BABYMETAL - any clue when this can be remedied?

**Comment by QavixRB** [comment]
Well Muse's starlight was uploaded before the package you downloaded has been uploaded so yeah btw the muse starlight is starlight2

**Comment by C0Assassin** [comment]
Should be fixed with latest AIO/PS3 pkg download.
