### ISSUE TITLE
Are there any plans to add all DLC here?

### ISSUE THREAD

**Issue by jakequi** [C0Assassin/rb4-to-rb2#8]
I've noticed quite a bit missing, and I completely understand why, but I am very curious as to whether you'll eventually add it all. 

Thanks.

**Comment by Tagark** [comment]
Not that this pertains to this issue, but I've been thrilled playing Rock Band 4 songs in rockband 2 format, is there any way to support your work, COAssaasin? Venmo or some sort?

**Comment by C0Assassin** [comment]
> I've noticed quite a bit missing, and I completely understand why, but I am very curious as to whether you'll eventually add it all.
> 
> Thanks.

This is an ongoing project, that might take years to fully complete. Not saying I'll do every song but I'll try.


> Not that this pertains to this issue, but I've been thrilled playing Rock Band 4 songs in rockband 2 format, is there any way to support your work, COAssaasin? Venmo or some sort?

A bit too obvious there, glowie.

**Comment by Tagark** [comment]
Just wanted to support your work. Meant nothing scammy by it.

**Comment by thoudankeykang** [comment]
sure buddy
