### ISSUE TITLE
360 DLC packs from 10/12/2022 not loading on hardware

### ISSUE THREAD

**Issue by Mirio23** [C0Assassin/RB4-to-RB2#9]
When loading both of the new DLC packs for the 360 from the spreadsheet, RB4toRB2-DLC-1 and RB4toRB2-DLC-2, the game immediately crashes when loading the packs to the cache. I tried to check both of them separately, but it happens in the case of both packs. I'm using both RB3DX as well as RBE.

I tried to depack some of the new songs (Nirvana and Muse) using C3CONTools and loaded those to the game as separate files. This way they seem to work just fine.

**Comment by C0Assassin** [comment]
Should be fixed with latest AIO update. Please DM jnack on discord in the future for anything related to the full pack downloads and the spreadsheet, as those are handled by him and not me.
